<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <!--
      Suppressions:
      1591: Missing XML comment (Compiler)
      SA1633: File Header
      CA1515: Make types internal
      SA1309: Field names must not start with underscore
      CA1031: Generic catch (Exception) - Allowed for top-level safety
    -->
    <NoWarn>$(NoWarn);1591;SA1633;CA1515;SA1309;CA1031</NoWarn>
    <AssemblyName>NvidiaControlPanel</AssemblyName>
    <RootNamespace>NvidiaControlPanel</RootNamespace>

    <!-- Optimization: Reduce Release Size -->
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <_SuppressWinFormsTrimError>true</_SuppressWinFormsTrimError>
    <_SuppressWpfTrimError>true</_SuppressWpfTrimError>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Resources\**\*.png" />
    <Resource Include="Resources\**\*.ico" />
    <Resource Include="..\..\assets\images\**\*.png" Link="Assets\Images\%(RecursiveDir)%(Filename)%(Extension)" />
    <Resource Include="icon.ico" />
    <None Update="GPU_Config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="..\..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro.IconPacks.SimpleIcons" Version="5.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.101">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="5.1.0" />
  </ItemGroup>

</Project>
